name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build
          run: |
            npm install
            npm run build
          env:
            REACT_APP_FTP_GAMES_DATABASE_API_KEY: ${{ secrets.REACT_APP_FTP_GAMES_DATABASE_API_KEY }}
            REACT_APP_GIANT_BOMB_API_KEY: ${{ secrets.REACT_APP_GIANT_BOMB_API_KEY }}

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
            folder: build
