name: Deploy to GitHub Pages
    on:
      push:
        branches:
          - master
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Build
          run: |
            npm install
            npm run build
          env:
            REACT_APP_FTP_GAMES_DATABASE_API_KEY: ${{ secrets.REACT_APP_FTP_GAMES_DATABASE_API_KEY }}
            REACT_APP_GIANT_BOMB_API_KEY: ${{ secrets.REACT_APP_GIANT_BOMB_API_KEY }}

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            BRANCH: gh-pages
            FOLDER: build
